language: node_js
node_js:
  - "7"
before_install: npm install -g mocha
install: npm install
before_script:
  - npm start
  - until curl -s localhost:3000; do true; done > /dev/null
after_script:
  - npm stop