language: node_js
node_js:
  - "node"
  - "7"
services:
  mongodb
before_install:
  - npm install -g mocha
  - npm install -g node-gyp node-pre-gyp
before_script:
  - node ./lib/initDb.js
  - npm start &
after_script:
  - npm stop
  - node ./lib/removeDb.js